version: '3.8'

services:
  # 1. Сервис PostgreSQL
  postgres:
    image: postgres:15
    container_name: myapp-postgres
    environment:
      POSTGRES_INITDB_SCHEMA: cringearium
      POSTGRES_INITDB_SCHEMA_GRANT: cringeadmin
      POSTGRES_DB: cringearium
      POSTGRES_USER: cringeadmin
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. Ваше Spring Boot приложение
  app:
    build: .
    container_name: myapp-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cringearium
      SPRING_DATASOURCE_USERNAME: cringeadmin
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - myapp-network
    restart: unless-stopped
    env_file:
      - .env

  # 3. Сервис Ollama с моделью deepseek:r1
  ollama:
    image: ollama/ollama
    expose:
      - 11434/tcp
    ports:
      - "11434:11434"
    healthcheck:
      test: ollama --version || exit 1
    entrypoint: /root/entrypoint.sh
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.sh:/root/entrypoint.sh

volumes:
  postgres_data:
  ollama_data:

networks:
  myapp-network:
    driver: bridge